services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db